/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "up2UService.h"

s_client listeClients[10];
int nb_clients = 0;

s_modele listeModeles[10];
int nb_modeles = 0;

s_assurance listeAssurances[10];
int nb_assurances = 0;

void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	printf("Initialisation du serveur\n");

	static char * result;

	strcpy(listeClients[0].nom, "PICART");
	strcpy(listeClients[0].prenom, "Mathieu");
	listeClients[0].adresse.codePostal = 29200;
	listeClients[0].adresse.numeroRue = 1;
	strcpy(listeClients[0].adresse.rue, "Rue de Roubaix");
	strcpy(listeClients[0].coordonneeBanc, "test");

	strcpy(listeClients[0].nom, "LE BEC");
	strcpy(listeClients[0].prenom, "Owen");
	listeClients[0].adresse.codePostal = 29200;
	listeClients[0].adresse.numeroRue = 1;
	strcpy(listeClients[0].adresse.rue, "Rue de Roubaix");
	strcpy(listeClients[0].coordonneeBanc, "test");
	
	nb_clients = 2;

	strcpy(listeModeles[0].nom, "Iphone X");
	strcpy(listeModeles[0].modele.description, "Au top !");
	listeModeles[0].modele.prix = 39.99;
	
	strcpy(listeModeles[1].modele.nom, "Galaxy S20");
	strcpy(listeModeles[1].modele.description, "Description...");
	listeModeles[1].modele.prix = 37.88;
	
	strcpy(listeModeles[2].modele.nom, "Galaxy S20+");
	strcpy(listeModeles[2].modele.description, "Description...");
	listeModeles[2].modele.prix = 42.04;
	
	nb_modeles = 3;



	return (void *) &result;
}

client *
create_client_1_svc(p_create_client *argp, struct svc_req *rqstp)
{
	static client  result;

	/*
	 * insert server code here
	 */

	return &result;
}

client *
set_client_1_svc(p_set_client *argp, struct svc_req *rqstp)
{
	static client  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
init_location_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

clients *
get_clients_1_svc(void *argp, struct svc_req *rqstp)
{
	static clients  result;

	/*
	 * insert server code here
	 */

	return &result;
}

client *
get_client_1_svc(int *argp, struct svc_req *rqstp)
{
	static client  result;

	/*
	 * insert server code here
	 */

	return &result;
}

location *
set_location_client_1_svc(client *argp, struct svc_req *rqstp)
{
	static location  result;

	/*
	 * insert server code here
	 */

	return &result;
}

mobile *
get_mobiles_1_svc(void *argp, struct svc_req *rqstp)
{
	static mobile  result;

	/*
	 * insert server code here
	 */

	return &result;
}

p_params_mobile *
get_mobile_params_1_svc(void *argp, struct svc_req *rqstp)
{
	static p_params_mobile  result;

	/*
	 * insert server code here
	 */

	return &result;
}

p_params_mobile *
set_params_mobile_1_svc(p_params_mobile *argp, struct svc_req *rqstp)
{
	static p_params_mobile  result;

	/*
	 * insert server code here
	 */

	return &result;
}

location *
set_location_mobile_1_svc(p_location_mobile *argp, struct svc_req *rqstp)
{
	static location  result;

	/*
	 * insert server code here
	 */

	return &result;
}

assurances *
get_assurances_1_svc(void *argp, struct svc_req *rqstp)
{
	static assurances  result;

	/*
	 * insert server code here
	 */

	return &result;
}

location *
set_location_assurances_1_svc(p_location_assurance *argp, struct svc_req *rqstp)
{
	static location  result;

	/*
	 * insert server code here
	 */

	return &result;
}

p_create_livraison *
create_livraison_1_svc(p_create_livraison *argp, struct svc_req *rqstp)
{
	static p_create_livraison  result;

	/*
	 * insert server code here
	 */

	return &result;
}
