/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "up2UService.h"

bool_t
xdr_couleur (XDR *xdrs, couleur *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_connectivite (XDR *xdrs, connectivite *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_memoire (XDR *xdrs, memoire *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_date (XDR *xdrs, date *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->jour))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mois))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->annee))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_adresse (XDR *xdrs, adresse *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->numeroRue))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->codePostal))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->rue, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_modele (XDR *xdrs, modele *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->description, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_appareil (XDR *xdrs, appareil *objp)
{
	register int32_t *buf;

	 if (!xdr_modele (xdrs, &objp->modele))
		 return FALSE;
	 if (!xdr_couleur (xdrs, &objp->couleur))
		 return FALSE;
	 if (!xdr_connectivite (xdrs, &objp->connectivite))
		 return FALSE;
	 if (!xdr_memoire (xdrs, &objp->memoire))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_location (XDR *xdrs, location *objp)
{
	register int32_t *buf;

	 if (!xdr_client (xdrs, &objp->client))
		 return FALSE;
	 if (!xdr_appareil (xdrs, &objp->appareil))
		 return FALSE;
	 if (!xdr_assurance (xdrs, &objp->assurance))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_assurance (XDR *xdrs, assurance *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->titre, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->description, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_client (XDR *xdrs, client *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_adresse (xdrs, &objp->adresse))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->coordonneeBanc, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_clients (XDR *xdrs, clients *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->clients, 5,
		sizeof (client), (xdrproc_t) xdr_client))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbClients))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_assurances (XDR *xdrs, assurances *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->assurances, 5,
		sizeof (assurance), (xdrproc_t) xdr_assurance))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbAssurances))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_create_client (XDR *xdrs, p_create_client *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_adresse (xdrs, &objp->adresse))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->coordonneeBanc, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_set_client (XDR *xdrs, p_set_client *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_adresse (xdrs, &objp->adresse))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->coordonneeBanc, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_params_mobile (XDR *xdrs, p_params_mobile *objp)
{
	register int32_t *buf;

	 if (!xdr_couleur (xdrs, &objp->couleur))
		 return FALSE;
	 if (!xdr_connectivite (xdrs, &objp->connectivite))
		 return FALSE;
	 if (!xdr_memoire (xdrs, &objp->memoire))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_location_mobile (XDR *xdrs, p_location_mobile *objp)
{
	register int32_t *buf;

	 if (!xdr_location (xdrs, &objp->location))
		 return FALSE;
	 if (!xdr_appareil (xdrs, &objp->appareil))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_location_assurance (XDR *xdrs, p_location_assurance *objp)
{
	register int32_t *buf;

	 if (!xdr_location (xdrs, &objp->location))
		 return FALSE;
	 if (!xdr_assurance (xdrs, &objp->assurance))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_create_livraison (XDR *xdrs, p_create_livraison *objp)
{
	register int32_t *buf;

	 if (!xdr_location (xdrs, &objp->location))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date))
		 return FALSE;
	return TRUE;
}
