/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "up2UService.h"

bool_t
xdr_e_couleur (XDR *xdrs, e_couleur *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_couleur (XDR *xdrs, couleur *objp)
{
	register int32_t *buf;

	 if (!xdr_e_couleur (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_e_connectivite (XDR *xdrs, e_connectivite *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_connectivite (XDR *xdrs, connectivite *objp)
{
	register int32_t *buf;

	 if (!xdr_e_connectivite (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_e_memoire (XDR *xdrs, e_memoire *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_memoire (XDR *xdrs, memoire *objp)
{
	register int32_t *buf;

	 if (!xdr_e_memoire (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_s_date (XDR *xdrs, s_date *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->jour))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mois))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->annee))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_s_adresse (XDR *xdrs, s_adresse *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->numeroRue))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->codePostal))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->rue, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_s_modele (XDR *xdrs, s_modele *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->description, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_s_appareil (XDR *xdrs, s_appareil *objp)
{
	register int32_t *buf;

	 if (!xdr_s_modele (xdrs, &objp->modele))
		 return FALSE;
	 if (!xdr_e_couleur (xdrs, &objp->couleur))
		 return FALSE;
	 if (!xdr_e_connectivite (xdrs, &objp->connectivite))
		 return FALSE;
	 if (!xdr_e_memoire (xdrs, &objp->memoire))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_s_location (XDR *xdrs, s_location *objp)
{
	register int32_t *buf;

	 if (!xdr_s_client (xdrs, &objp->client))
		 return FALSE;
	 if (!xdr_s_appareil (xdrs, &objp->appareil))
		 return FALSE;
	 if (!xdr_s_assurance (xdrs, &objp->assurance))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_s_assurance (XDR *xdrs, s_assurance *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->titre, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->description, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_s_client (XDR *xdrs, s_client *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_s_adresse (xdrs, &objp->adresse))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->coordonneeBanc, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_s_clients (XDR *xdrs, s_clients *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->clients, 5,
		sizeof (s_client), (xdrproc_t) xdr_s_client))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbClients))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_s_assurances (XDR *xdrs, s_assurances *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->assurances, 5,
		sizeof (s_assurance), (xdrproc_t) xdr_s_assurance))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbAssurances))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_create_client (XDR *xdrs, p_create_client *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numeroRue))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->codePostal))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->rue, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->coordonneeBanc, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_set_client (XDR *xdrs, p_set_client *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_s_adresse (xdrs, &objp->adresse))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->coordonneeBanc, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_params_mobile (XDR *xdrs, p_params_mobile *objp)
{
	register int32_t *buf;

	 if (!xdr_couleur (xdrs, &objp->couleur))
		 return FALSE;
	 if (!xdr_connectivite (xdrs, &objp->connectivite))
		 return FALSE;
	 if (!xdr_memoire (xdrs, &objp->memoire))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_location_mobile (XDR *xdrs, p_location_mobile *objp)
{
	register int32_t *buf;

	 if (!xdr_s_location (xdrs, &objp->location))
		 return FALSE;
	 if (!xdr_s_appareil (xdrs, &objp->appareil))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_location_assurance (XDR *xdrs, p_location_assurance *objp)
{
	register int32_t *buf;

	 if (!xdr_s_location (xdrs, &objp->location))
		 return FALSE;
	 if (!xdr_s_assurance (xdrs, &objp->assurance))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_p_create_livraison (XDR *xdrs, p_create_livraison *objp)
{
	register int32_t *buf;

	 if (!xdr_s_location (xdrs, &objp->location))
		 return FALSE;
	 if (!xdr_s_date (xdrs, &objp->date))
		 return FALSE;
	return TRUE;
}
