/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UP2USERVICE_H_RPCGEN
#define _UP2USERVICE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum couleur {
	ROUGE = 0,
	VERT = 1,
	NOIR = 2,
	BLANC = 3,
};
typedef enum couleur couleur;


enum connectivite {
	G4 = 0,
	G5 = 1,
};
typedef enum connectivite connectivite;


enum memoire {
	GO128 = 0,
	GO256 = 1,
	GO512 = 2,
};
typedef enum memoire memoire;


struct date {
	int jour;
	int mois;
	int annee;
};
typedef struct date date;

struct adresse {
	int numeroRue;
	int codePostal;
	char rue[30];
};
typedef struct adresse adresse;

struct modele {
	char nom[15];
	float prix;
	char description[255];
};
typedef struct modele modele;

struct appareil {
	modele modele;
	couleur couleur;
	connectivite connectivite;
	memoire memoire;
};
typedef struct appareil appareil;

struct location {
	client client;
	appareil appareil;
	assurance assurance;
};
typedef struct location location;

struct assurance {
	char titre[15];
	float prix;
	char description[255];
};
typedef struct assurance assurance;

struct client {
	char nom[15];
	char prenom[15];
	adresse adresse;
	char coordonneeBanc[100];
};
typedef struct client client;

struct clients {
	client clients[5];
	int nbClients;
};
typedef struct clients clients;

struct assurances {
	assurance assurances[5];
	int nbAssurances;
};
typedef struct assurances assurances;

struct p_create_client {
	char nom[15];
	char prenom[15];
	adresse adresse;
	char coordonneeBanc[30];
};
typedef struct p_create_client p_create_client;

struct p_set_client {
	int id;
	char nom[15];
	char prenom[15];
	adresse adresse;
	char coordonneeBanc[30];
};
typedef struct p_set_client p_set_client;

struct p_params_mobile {
	couleur couleur;
	connectivite connectivite;
	memoire memoire;
};
typedef struct p_params_mobile p_params_mobile;

struct p_location_mobile {
	location location;
	appareil appareil;
};
typedef struct p_location_mobile p_location_mobile;

struct p_location_assurance {
	location location;
	assurance assurance;
};
typedef struct p_location_assurance p_location_assurance;

struct p_create_livraison {
	location location;
	date date;
};
typedef struct p_create_livraison p_create_livraison;

#define UP2USERVICE 0x23456789
#define UP2USERVICE_V_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT 1
extern  void * init_1(void *, CLIENT *);
extern  void * init_1_svc(void *, struct svc_req *);
#define CREATE_CLIENT 2
extern  client * create_client_1(p_create_client *, CLIENT *);
extern  client * create_client_1_svc(p_create_client *, struct svc_req *);
#define SET_CLIENT 3
extern  client * set_client_1(p_set_client *, CLIENT *);
extern  client * set_client_1_svc(p_set_client *, struct svc_req *);
#define INIT_LOCATION 4
extern  int * init_location_1(void *, CLIENT *);
extern  int * init_location_1_svc(void *, struct svc_req *);
#define GET_CLIENTS 5
extern  clients * get_clients_1(void *, CLIENT *);
extern  clients * get_clients_1_svc(void *, struct svc_req *);
#define GET_CLIENT 6
extern  client * get_client_1(int *, CLIENT *);
extern  client * get_client_1_svc(int *, struct svc_req *);
#define SET_LOCATION_CLIENT 7
extern  location * set_location_client_1(client *, CLIENT *);
extern  location * set_location_client_1_svc(client *, struct svc_req *);
#define GET_MOBILES 8
extern  mobile * get_mobiles_1(void *, CLIENT *);
extern  mobile * get_mobiles_1_svc(void *, struct svc_req *);
#define GET_MOBILE_PARAMS 9
extern  p_params_mobile * get_mobile_params_1(void *, CLIENT *);
extern  p_params_mobile * get_mobile_params_1_svc(void *, struct svc_req *);
#define SET_PARAMS_MOBILE 10
extern  p_params_mobile * set_params_mobile_1(p_params_mobile *, CLIENT *);
extern  p_params_mobile * set_params_mobile_1_svc(p_params_mobile *, struct svc_req *);
#define SET_LOCATION_MOBILE 11
extern  location * set_location_mobile_1(p_location_mobile *, CLIENT *);
extern  location * set_location_mobile_1_svc(p_location_mobile *, struct svc_req *);
#define GET_ASSURANCES 12
extern  assurances * get_assurances_1(void *, CLIENT *);
extern  assurances * get_assurances_1_svc(void *, struct svc_req *);
#define SET_LOCATION_ASSURANCES 13
extern  location * set_location_assurances_1(p_location_assurance *, CLIENT *);
extern  location * set_location_assurances_1_svc(p_location_assurance *, struct svc_req *);
#define CREATE_LIVRAISON 14
extern  p_create_livraison * create_livraison_1(p_create_livraison *, CLIENT *);
extern  p_create_livraison * create_livraison_1_svc(p_create_livraison *, struct svc_req *);
extern int up2uservice_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT 1
extern  void * init_1();
extern  void * init_1_svc();
#define CREATE_CLIENT 2
extern  client * create_client_1();
extern  client * create_client_1_svc();
#define SET_CLIENT 3
extern  client * set_client_1();
extern  client * set_client_1_svc();
#define INIT_LOCATION 4
extern  int * init_location_1();
extern  int * init_location_1_svc();
#define GET_CLIENTS 5
extern  clients * get_clients_1();
extern  clients * get_clients_1_svc();
#define GET_CLIENT 6
extern  client * get_client_1();
extern  client * get_client_1_svc();
#define SET_LOCATION_CLIENT 7
extern  location * set_location_client_1();
extern  location * set_location_client_1_svc();
#define GET_MOBILES 8
extern  mobile * get_mobiles_1();
extern  mobile * get_mobiles_1_svc();
#define GET_MOBILE_PARAMS 9
extern  p_params_mobile * get_mobile_params_1();
extern  p_params_mobile * get_mobile_params_1_svc();
#define SET_PARAMS_MOBILE 10
extern  p_params_mobile * set_params_mobile_1();
extern  p_params_mobile * set_params_mobile_1_svc();
#define SET_LOCATION_MOBILE 11
extern  location * set_location_mobile_1();
extern  location * set_location_mobile_1_svc();
#define GET_ASSURANCES 12
extern  assurances * get_assurances_1();
extern  assurances * get_assurances_1_svc();
#define SET_LOCATION_ASSURANCES 13
extern  location * set_location_assurances_1();
extern  location * set_location_assurances_1_svc();
#define CREATE_LIVRAISON 14
extern  p_create_livraison * create_livraison_1();
extern  p_create_livraison * create_livraison_1_svc();
extern int up2uservice_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_couleur (XDR *, couleur*);
extern  bool_t xdr_couleur (XDR *, couleur*);
extern  bool_t xdr_connectivite (XDR *, connectivite*);
extern  bool_t xdr_connectivite (XDR *, connectivite*);
extern  bool_t xdr_memoire (XDR *, memoire*);
extern  bool_t xdr_memoire (XDR *, memoire*);
extern  bool_t xdr_date (XDR *, date*);
extern  bool_t xdr_adresse (XDR *, adresse*);
extern  bool_t xdr_modele (XDR *, modele*);
extern  bool_t xdr_appareil (XDR *, appareil*);
extern  bool_t xdr_location (XDR *, location*);
extern  bool_t xdr_assurance (XDR *, assurance*);
extern  bool_t xdr_client (XDR *, client*);
extern  bool_t xdr_clients (XDR *, clients*);
extern  bool_t xdr_assurances (XDR *, assurances*);
extern  bool_t xdr_p_create_client (XDR *, p_create_client*);
extern  bool_t xdr_p_set_client (XDR *, p_set_client*);
extern  bool_t xdr_p_params_mobile (XDR *, p_params_mobile*);
extern  bool_t xdr_p_location_mobile (XDR *, p_location_mobile*);
extern  bool_t xdr_p_location_assurance (XDR *, p_location_assurance*);
extern  bool_t xdr_p_create_livraison (XDR *, p_create_livraison*);

#else /* K&R C */
extern bool_t xdr_couleur ();
extern bool_t xdr_couleur ();
extern bool_t xdr_connectivite ();
extern bool_t xdr_connectivite ();
extern bool_t xdr_memoire ();
extern bool_t xdr_memoire ();
extern bool_t xdr_date ();
extern bool_t xdr_adresse ();
extern bool_t xdr_modele ();
extern bool_t xdr_appareil ();
extern bool_t xdr_location ();
extern bool_t xdr_assurance ();
extern bool_t xdr_client ();
extern bool_t xdr_clients ();
extern bool_t xdr_assurances ();
extern bool_t xdr_p_create_client ();
extern bool_t xdr_p_set_client ();
extern bool_t xdr_p_params_mobile ();
extern bool_t xdr_p_location_mobile ();
extern bool_t xdr_p_location_assurance ();
extern bool_t xdr_p_create_livraison ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UP2USERVICE_H_RPCGEN */
