/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UP2USERVICE_H_RPCGEN
#define _UP2USERVICE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum e_couleur {
	ROUGE = 0,
	VERT = 1,
	NOIR = 2,
	BLANC = 3,
};
typedef enum e_couleur e_couleur;

typedef e_couleur couleur;

enum e_connectivite {
	G4 = 0,
	G5 = 1,
};
typedef enum e_connectivite e_connectivite;

typedef e_connectivite connectivite;

enum e_memoire {
	GO128 = 0,
	GO256 = 1,
	GO512 = 2,
};
typedef enum e_memoire e_memoire;

typedef e_memoire memoire;

struct s_date {
	int jour;
	int mois;
	int annee;
};
typedef struct s_date s_date;

struct s_adresse {
	int numeroRue;
	int codePostal;
	char rue[30];
};
typedef struct s_adresse s_adresse;

struct s_modele {
	char nom[15];
	float prix;
	char description[255];
};
typedef struct s_modele s_modele;

struct s_appareil {
	s_modele modele;
	e_couleur couleur;
	e_connectivite connectivite;
	e_memoire memoire;
};
typedef struct s_appareil s_appareil;

struct s_location {
	s_client client;
	s_appareil appareil;
	s_assurance assurance;
};
typedef struct s_location s_location;

struct s_assurance {
	char titre[15];
	float prix;
	char description[255];
};
typedef struct s_assurance s_assurance;

struct s_client {
	char nom[15];
	char prenom[15];
	s_adresse adresse;
	char coordonneeBanc[100];
};
typedef struct s_client s_client;

struct s_clients {
	s_client clients[5];
	int nbClients;
};
typedef struct s_clients s_clients;

struct s_assurances {
	s_assurance assurances[5];
	int nbAssurances;
};
typedef struct s_assurances s_assurances;

struct p_create_client {
	char nom[15];
	char prenom[15];
	int numeroRue;
	int codePostal;
	char rue[30];
	char coordonneeBanc[30];
};
typedef struct p_create_client p_create_client;

struct p_set_client {
	int id;
	char nom[15];
	char prenom[15];
	s_adresse adresse;
	char coordonneeBanc[30];
};
typedef struct p_set_client p_set_client;

struct p_params_mobile {
	couleur couleur;
	connectivite connectivite;
	memoire memoire;
};
typedef struct p_params_mobile p_params_mobile;

struct p_location_mobile {
	s_location location;
	s_appareil appareil;
};
typedef struct p_location_mobile p_location_mobile;

struct p_location_assurance {
	s_location location;
	s_assurance assurance;
};
typedef struct p_location_assurance p_location_assurance;

struct p_create_livraison {
	s_location location;
	s_date date;
};
typedef struct p_create_livraison p_create_livraison;

#define UP2USERVICE 0x23456789
#define UP2USERVICE_V_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT 1
extern  void * init_1(void *, CLIENT *);
extern  void * init_1_svc(void *, struct svc_req *);
#define CREATE_CLIENT 2
extern  s_client * create_client_1(p_create_client *, CLIENT *);
extern  s_client * create_client_1_svc(p_create_client *, struct svc_req *);
#define SET_CLIENT 3
extern  s_client * set_client_1(p_set_client *, CLIENT *);
extern  s_client * set_client_1_svc(p_set_client *, struct svc_req *);
#define INIT_LOCATION 4
extern  int * init_location_1(void *, CLIENT *);
extern  int * init_location_1_svc(void *, struct svc_req *);
#define GET_CLIENTS 5
extern  s_clients * get_clients_1(void *, CLIENT *);
extern  s_clients * get_clients_1_svc(void *, struct svc_req *);
#define GET_CLIENT 6
extern  s_client * get_client_1(int *, CLIENT *);
extern  s_client * get_client_1_svc(int *, struct svc_req *);
#define SET_LOCATION_CLIENT 7
extern  s_location * set_location_client_1(s_client *, CLIENT *);
extern  s_location * set_location_client_1_svc(s_client *, struct svc_req *);
#define GET_MOBILES 8
extern  s_modele * get_mobiles_1(void *, CLIENT *);
extern  s_modele * get_mobiles_1_svc(void *, struct svc_req *);
#define GET_MOBILE_PARAMS 9
extern  p_params_mobile * get_mobile_params_1(void *, CLIENT *);
extern  p_params_mobile * get_mobile_params_1_svc(void *, struct svc_req *);
#define SET_PARAMS_MOBILE 10
extern  p_params_mobile * set_params_mobile_1(p_params_mobile *, CLIENT *);
extern  p_params_mobile * set_params_mobile_1_svc(p_params_mobile *, struct svc_req *);
#define SET_LOCATION_MOBILE 11
extern  s_location * set_location_mobile_1(p_location_mobile *, CLIENT *);
extern  s_location * set_location_mobile_1_svc(p_location_mobile *, struct svc_req *);
#define GET_ASSURANCES 12
extern  s_assurances * get_assurances_1(void *, CLIENT *);
extern  s_assurances * get_assurances_1_svc(void *, struct svc_req *);
#define SET_LOCATION_ASSURANCES 13
extern  s_location * set_location_assurances_1(p_location_assurance *, CLIENT *);
extern  s_location * set_location_assurances_1_svc(p_location_assurance *, struct svc_req *);
#define CREATE_LIVRAISON 14
extern  p_create_livraison * create_livraison_1(p_create_livraison *, CLIENT *);
extern  p_create_livraison * create_livraison_1_svc(p_create_livraison *, struct svc_req *);
extern int up2uservice_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT 1
extern  void * init_1();
extern  void * init_1_svc();
#define CREATE_CLIENT 2
extern  client * create_client_1();
extern  client * create_client_1_svc();
#define SET_CLIENT 3
extern  client * set_client_1();
extern  client * set_client_1_svc();
#define INIT_LOCATION 4
extern  int * init_location_1();
extern  int * init_location_1_svc();
#define GET_CLIENTS 5
extern  clients * get_clients_1();
extern  clients * get_clients_1_svc();
#define GET_CLIENT 6
extern  client * get_client_1();
extern  client * get_client_1_svc();
#define SET_LOCATION_CLIENT 7
extern  location * set_location_client_1();
extern  location * set_location_client_1_svc();
#define GET_MOBILES 8
extern  mobile * get_mobiles_1();
extern  mobile * get_mobiles_1_svc();
#define GET_MOBILE_PARAMS 9
extern  p_params_mobile * get_mobile_params_1();
extern  p_params_mobile * get_mobile_params_1_svc();
#define SET_PARAMS_MOBILE 10
extern  p_params_mobile * set_params_mobile_1();
extern  p_params_mobile * set_params_mobile_1_svc();
#define SET_LOCATION_MOBILE 11
extern  location * set_location_mobile_1();
extern  location * set_location_mobile_1_svc();
#define GET_ASSURANCES 12
extern  assurances * get_assurances_1();
extern  assurances * get_assurances_1_svc();
#define SET_LOCATION_ASSURANCES 13
extern  location * set_location_assurances_1();
extern  location * set_location_assurances_1_svc();
#define CREATE_LIVRAISON 14
extern  p_create_livraison * create_livraison_1();
extern  p_create_livraison * create_livraison_1_svc();
extern int up2uservice_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_e_couleur (XDR *, e_couleur*);
extern  bool_t xdr_couleur (XDR *, couleur*);
extern  bool_t xdr_e_connectivite (XDR *, e_connectivite*);
extern  bool_t xdr_connectivite (XDR *, connectivite*);
extern  bool_t xdr_e_memoire (XDR *, e_memoire*);
extern  bool_t xdr_memoire (XDR *, memoire*);
extern  bool_t xdr_s_date (XDR *, s_date*);
extern  bool_t xdr_s_adresse (XDR *, s_adresse*);
extern  bool_t xdr_s_modele (XDR *, s_modele*);
extern  bool_t xdr_s_appareil (XDR *, s_appareil*);
extern  bool_t xdr_s_location (XDR *, s_location*);
extern  bool_t xdr_s_assurance (XDR *, s_assurance*);
extern  bool_t xdr_s_client (XDR *, s_client*);
extern  bool_t xdr_s_clients (XDR *, s_clients*);
extern  bool_t xdr_s_assurances (XDR *, s_assurances*);
extern  bool_t xdr_p_create_client (XDR *, p_create_client*);
extern  bool_t xdr_p_set_client (XDR *, p_set_client*);
extern  bool_t xdr_p_params_mobile (XDR *, p_params_mobile*);
extern  bool_t xdr_p_location_mobile (XDR *, p_location_mobile*);
extern  bool_t xdr_p_location_assurance (XDR *, p_location_assurance*);
extern  bool_t xdr_p_create_livraison (XDR *, p_create_livraison*);

#else /* K&R C */
extern bool_t xdr_e_couleur ();
extern bool_t xdr_couleur ();
extern bool_t xdr_e_connectivite ();
extern bool_t xdr_connectivite ();
extern bool_t xdr_e_memoire ();
extern bool_t xdr_memoire ();
extern bool_t xdr_s_date ();
extern bool_t xdr_s_adresse ();
extern bool_t xdr_s_modele ();
extern bool_t xdr_s_appareil ();
extern bool_t xdr_s_location ();
extern bool_t xdr_s_assurance ();
extern bool_t xdr_s_client ();
extern bool_t xdr_s_clients ();
extern bool_t xdr_s_assurances ();
extern bool_t xdr_p_create_client ();
extern bool_t xdr_p_set_client ();
extern bool_t xdr_p_params_mobile ();
extern bool_t xdr_p_location_mobile ();
extern bool_t xdr_p_location_assurance ();
extern bool_t xdr_p_create_livraison ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UP2USERVICE_H_RPCGEN */
