/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UP2USERVICE_H_RPCGEN
#define _UP2USERVICE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum e_couleur {
	ROUGE = 0,
	VERT = 1,
	NOIR = 2,
	BLANC = 3,
};
typedef enum e_couleur e_couleur;

typedef e_couleur couleur;

enum e_connectivite {
	G4 = 0,
	G5 = 1,
};
typedef enum e_connectivite e_connectivite;

typedef e_connectivite connectivite;

enum e_memoire {
	GO128 = 0,
	GO256 = 1,
	GO512 = 2,
};
typedef enum e_memoire e_memoire;

typedef e_memoire memoire;

enum e_mode_achat {
	location = 0,
	achat = 1,
};
typedef enum e_mode_achat e_mode_achat;

typedef e_mode_achat mode_achat;

struct s_date {
	int jour;
	int mois;
	int annee;
};
typedef struct s_date s_date;

struct s_coord_bc {
	long numero;
	int crypto;
	int mois;
	int annee;
};
typedef struct s_coord_bc s_coord_bc;

struct s_adresse {
	int numeroRue;
	int codePostal;
	char rue[30];
};
typedef struct s_adresse s_adresse;

struct s_modele {
	int id;
	char nom[15];
	float prix_achat;
	float prix_location;
	char description[255];
};
typedef struct s_modele s_modele;

struct s_params_modele {
	int id_modele;
	e_couleur couleur;
	e_connectivite connectivite;
	e_memoire memoire;
	e_mode_achat mode_achat;
};
typedef struct s_params_modele s_params_modele;

struct s_client {
	int id;
	char nom[15];
	char prenom[15];
	s_adresse adresse;
	s_coord_bc coord_bc;
};
typedef struct s_client s_client;

struct s_assurance {
	int id;
	char titre[15];
	float prix;
	char description[255];
};
typedef struct s_assurance s_assurance;

struct s_location {
	int id;
	int id_client;
	int id_modele;
	s_params_modele params_modele;
	int id_assurance;
	int confirme;
	s_date date_livraison;
};
typedef struct s_location s_location;

struct listeClients {
	s_client client[10];
	int nb_clients;
};
typedef struct listeClients listeClients;

struct listeAssurances {
	s_assurance assurances[10];
	int nb_assurances;
};
typedef struct listeAssurances listeAssurances;

struct listeModeles {
	s_modele modeles[10];
	int nb_modeles;
};
typedef struct listeModeles listeModeles;

struct listeModelesParams {
	s_params_modele params_modele[10];
	int nb_modele_params;
};
typedef struct listeModelesParams listeModelesParams;

struct p_create_client {
	char nom[15];
	char prenom[15];
	s_adresse adresse;
	s_coord_bc coord_bc;
};
typedef struct p_create_client p_create_client;

struct p_set_client {
	int id;
	char nom[15];
	char prenom[15];
	s_adresse adresse;
	s_coord_bc coord_bc;
};
typedef struct p_set_client p_set_client;

struct p_location_client {
	int id_location;
	int id_client;
};
typedef struct p_location_client p_location_client;

struct p_location_modele {
	int id_location;
	int id_modele;
};
typedef struct p_location_modele p_location_modele;

struct p_location_params_modele {
	int id_location;
	s_params_modele params_modele;
};
typedef struct p_location_params_modele p_location_params_modele;

struct p_location_assurance {
	int id_location;
	int id_assurance;
};
typedef struct p_location_assurance p_location_assurance;

struct p_location_date {
	int id_location;
	s_date date_livraison;
};
typedef struct p_location_date p_location_date;

#define UP2USERVICE 0x23456789
#define UP2USERVICE_V_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT 1
extern  void * init_1(void *, CLIENT *);
extern  void * init_1_svc(void *, struct svc_req *);
#define CREATE_CLIENT 2
extern  int * create_client_1(p_create_client *, CLIENT *);
extern  int * create_client_1_svc(p_create_client *, struct svc_req *);
#define SET_CLIENT 3
extern  int * set_client_1(p_set_client *, CLIENT *);
extern  int * set_client_1_svc(p_set_client *, struct svc_req *);
#define GET_CLIENTS 4
extern  listeClients * get_clients_1(void *, CLIENT *);
extern  listeClients * get_clients_1_svc(void *, struct svc_req *);
#define SET_LOCATION_CLIENT 5
extern  int * set_location_client_1(p_location_client *, CLIENT *);
extern  int * set_location_client_1_svc(p_location_client *, struct svc_req *);
#define GET_MODELES 6
extern  listeModeles * get_modeles_1(void *, CLIENT *);
extern  listeModeles * get_modeles_1_svc(void *, struct svc_req *);
#define SET_LOCATION_MODELE 7
extern  int * set_location_modele_1(p_location_modele *, CLIENT *);
extern  int * set_location_modele_1_svc(p_location_modele *, struct svc_req *);
#define GET_MODELE_PARAMS 8
extern  listeModelesParams * get_modele_params_1(int *, CLIENT *);
extern  listeModelesParams * get_modele_params_1_svc(int *, struct svc_req *);
#define SET_LOCATION_MODELE_PARAMS 9
extern  int * set_location_modele_params_1(p_location_params_modele *, CLIENT *);
extern  int * set_location_modele_params_1_svc(p_location_params_modele *, struct svc_req *);
#define GET_ASSURANCES 10
extern  listeAssurances * get_assurances_1(void *, CLIENT *);
extern  listeAssurances * get_assurances_1_svc(void *, struct svc_req *);
#define SET_LOCATION_ASSURANCE 11
extern  int * set_location_assurance_1(p_location_assurance *, CLIENT *);
extern  int * set_location_assurance_1_svc(p_location_assurance *, struct svc_req *);
#define SET_LOCATION_DATE 12
extern  int * set_location_date_1(p_location_date *, CLIENT *);
extern  int * set_location_date_1_svc(p_location_date *, struct svc_req *);
#define CONFIRMER_LOCATION 13
extern  int * confirmer_location_1(int *, CLIENT *);
extern  int * confirmer_location_1_svc(int *, struct svc_req *);
extern int up2uservice_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT 1
extern  void * init_1();
extern  void * init_1_svc();
#define CREATE_CLIENT 2
extern  int * create_client_1();
extern  int * create_client_1_svc();
#define SET_CLIENT 3
extern  int * set_client_1();
extern  int * set_client_1_svc();
#define GET_CLIENTS 4
extern  listeClients * get_clients_1();
extern  listeClients * get_clients_1_svc();
#define SET_LOCATION_CLIENT 5
extern  int * set_location_client_1();
extern  int * set_location_client_1_svc();
#define GET_MODELES 6
extern  listeModeles * get_modeles_1();
extern  listeModeles * get_modeles_1_svc();
#define SET_LOCATION_MODELE 7
extern  int * set_location_modele_1();
extern  int * set_location_modele_1_svc();
#define GET_MODELE_PARAMS 8
extern  listeModelesParams * get_modele_params_1();
extern  listeModelesParams * get_modele_params_1_svc();
#define SET_LOCATION_MODELE_PARAMS 9
extern  int * set_location_modele_params_1();
extern  int * set_location_modele_params_1_svc();
#define GET_ASSURANCES 10
extern  listeAssurances * get_assurances_1();
extern  listeAssurances * get_assurances_1_svc();
#define SET_LOCATION_ASSURANCE 11
extern  int * set_location_assurance_1();
extern  int * set_location_assurance_1_svc();
#define SET_LOCATION_DATE 12
extern  int * set_location_date_1();
extern  int * set_location_date_1_svc();
#define CONFIRMER_LOCATION 13
extern  int * confirmer_location_1();
extern  int * confirmer_location_1_svc();
extern int up2uservice_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_e_couleur (XDR *, e_couleur*);
extern  bool_t xdr_couleur (XDR *, couleur*);
extern  bool_t xdr_e_connectivite (XDR *, e_connectivite*);
extern  bool_t xdr_connectivite (XDR *, connectivite*);
extern  bool_t xdr_e_memoire (XDR *, e_memoire*);
extern  bool_t xdr_memoire (XDR *, memoire*);
extern  bool_t xdr_e_mode_achat (XDR *, e_mode_achat*);
extern  bool_t xdr_mode_achat (XDR *, mode_achat*);
extern  bool_t xdr_s_date (XDR *, s_date*);
extern  bool_t xdr_s_coord_bc (XDR *, s_coord_bc*);
extern  bool_t xdr_s_adresse (XDR *, s_adresse*);
extern  bool_t xdr_s_modele (XDR *, s_modele*);
extern  bool_t xdr_s_params_modele (XDR *, s_params_modele*);
extern  bool_t xdr_s_client (XDR *, s_client*);
extern  bool_t xdr_s_assurance (XDR *, s_assurance*);
extern  bool_t xdr_s_location (XDR *, s_location*);
extern  bool_t xdr_listeClients (XDR *, listeClients*);
extern  bool_t xdr_listeAssurances (XDR *, listeAssurances*);
extern  bool_t xdr_listeModeles (XDR *, listeModeles*);
extern  bool_t xdr_listeModelesParams (XDR *, listeModelesParams*);
extern  bool_t xdr_p_create_client (XDR *, p_create_client*);
extern  bool_t xdr_p_set_client (XDR *, p_set_client*);
extern  bool_t xdr_p_location_client (XDR *, p_location_client*);
extern  bool_t xdr_p_location_modele (XDR *, p_location_modele*);
extern  bool_t xdr_p_location_params_modele (XDR *, p_location_params_modele*);
extern  bool_t xdr_p_location_assurance (XDR *, p_location_assurance*);
extern  bool_t xdr_p_location_date (XDR *, p_location_date*);

#else /* K&R C */
extern bool_t xdr_e_couleur ();
extern bool_t xdr_couleur ();
extern bool_t xdr_e_connectivite ();
extern bool_t xdr_connectivite ();
extern bool_t xdr_e_memoire ();
extern bool_t xdr_memoire ();
extern bool_t xdr_e_mode_achat ();
extern bool_t xdr_mode_achat ();
extern bool_t xdr_s_date ();
extern bool_t xdr_s_coord_bc ();
extern bool_t xdr_s_adresse ();
extern bool_t xdr_s_modele ();
extern bool_t xdr_s_params_modele ();
extern bool_t xdr_s_client ();
extern bool_t xdr_s_assurance ();
extern bool_t xdr_s_location ();
extern bool_t xdr_listeClients ();
extern bool_t xdr_listeAssurances ();
extern bool_t xdr_listeModeles ();
extern bool_t xdr_listeModelesParams ();
extern bool_t xdr_p_create_client ();
extern bool_t xdr_p_set_client ();
extern bool_t xdr_p_location_client ();
extern bool_t xdr_p_location_modele ();
extern bool_t xdr_p_location_params_modele ();
extern bool_t xdr_p_location_assurance ();
extern bool_t xdr_p_location_date ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UP2USERVICE_H_RPCGEN */
