/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "up2UService.h"

void afficherClient(s_client client)
{
	printf("\t%s\n", client.nom);
	printf("\t%s\n", client.prenom);
	printf("\t%d %s %d\n", client.adresse.numeroRue, client.adresse.rue, client.adresse.codePostal);
	printf("\tCoordonnee Bancaire :\n");
	printf("\t\t%ld %d %d/%d\n", client.coord_bc.numero, client.coord_bc.crypto, client.coord_bc.mois, client.coord_bc.annee);
}

void afficherAssurances(s_assurance assurance)
{
	printf("\t%s\n", assurance.titre);
	printf("\t%s\n", assurance.description);
	printf("\t%.2f euros\n", assurance.prix);
}

void afficherModele(s_modele modele)
{
	printf("\t%s\n", modele.nom);
	printf("\tPrix d'achat : %.2f\n", modele.prix_achat);
	printf("\tPrix de location : %.2f\n", modele.prix_location);
	printf("\t%s\n", modele.description);
}

void
up2uservice_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *init_1_arg;
	int  *result_2;
	p_create_client  create_client_1_arg;
	int  *result_3;
	p_set_client  set_client_1_arg;
	listeClients  *result_4;
	char *get_clients_1_arg;
	int  *result_5;
	p_location_client  set_location_client_1_arg;
	listeModeles  *result_6;
	char *get_modeles_1_arg;
	int  *result_7;
	p_location_modele  set_location_modele_1_arg;
	listeModelesParams  *result_8;
	int  get_modele_params_1_arg;
	int  *result_9;
	p_location_params_modele  set_location_modele_params_1_arg;
	listeAssurances  *result_10;
	char *get_assurances_1_arg;
	int  *result_11;
	p_location_assurance  set_location_assurance_1_arg;
	int  *result_12;
	p_location_date  set_location_date_1_arg;
	int  *result_13;
	int  confirmer_location_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, UP2USERVICE, UP2USERVICE_V_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = init_1((void*)&init_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Serveur initialisé !\n");

	printf("=========================================\n");

	strcpy(create_client_1_arg.nom, "DUPONT");
	strcpy(create_client_1_arg.prenom, "Jean");
	create_client_1_arg.adresse.codePostal = 36450;
	create_client_1_arg.adresse.numeroRue = 12;
	strcpy(create_client_1_arg.adresse.rue, "Chemin del papa");
	create_client_1_arg.coord_bc.numero = 6412333356766934;
	create_client_1_arg.coord_bc.crypto = 373;
	create_client_1_arg.coord_bc.mois = 12;
	create_client_1_arg.coord_bc.annee = 2025;

	printf("Ajout du client\n");

	result_2 = create_client_1(&create_client_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf(result_2==0?"Client ajouté\n":"Trop de Client\n");

	printf("=========================================\n");

	set_client_1_arg.id = 2;
	strcpy(set_client_1_arg.nom, "CASTEX");
	strcpy(set_client_1_arg.prenom, "Janot");
	set_client_1_arg.coord_bc.numero = 6412374856766934;
	set_client_1_arg.coord_bc.crypto = 694;
	set_client_1_arg.coord_bc.mois = 01;
	set_client_1_arg.coord_bc.annee = 2024;
	set_client_1_arg.adresse.codePostal = 22600;
	set_client_1_arg.adresse.numeroRue = 45;
	strcpy(set_client_1_arg.adresse.rue, "Chemin du paradis");

	printf("Modification du client\n");

	result_3 = set_client_1(&set_client_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf(result_3==0?"Modification du client effectué\n":"Client non trouvé\n");

	printf("=========================================\n");

	printf("Recuperation des clients\n");

	result_4 = get_clients_1((void*)&get_clients_1_arg, clnt);
	if (result_4 == (listeClients *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Affichage des clients\n");

		for (int i = 0; i < result_4->nb_clients; i++)
		{
			printf("\nClient n°%d\n", i);
			afficherClient(result_4->client[i]);
		}
	}

	printf("=========================================\n");

	set_location_client_1_arg.id_location = 0;
	set_location_client_1_arg.id_client = 2;

	printf("Enregistrement du client pour la location\n");

	result_5 = set_location_client_1(&set_location_client_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf(result_5==0?"Enregistrement du client effectué\n":"\n");

	printf("=========================================\n");
	
	printf("Recuperation des modeles\n");
	
	result_6 = get_modeles_1((void*)&get_modeles_1_arg, clnt);
	if (result_6 == (listeModeles *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Affichage des modeles\n");

		for (int i = 0; i < result_6->nb_modele; i++)
		{
			printf("\nModele n°%d\n", i);
			afficherModele(result_6->modeles[i]);
		}
	}
	
	printf("=========================================\n");

	set_location_modele_1_arg.id_location = 0;
	set_location_modele_1_arg.id_modele = 1;

	printf("Enregistrement du modele pour la location\n");

	result_7 = set_location_modele_1(&set_location_modele_1_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Enregistrement du modele effectué\n");

	printf("=========================================\n");	

	get_modele_params_1_arg = 1;

	printf("Recuperation des parametres disponible\n");

	result_8 = get_modele_params_1(&get_modele_params_1_arg, clnt);
	if (result_8 == (listeModelesParams *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Affichage des parametres\n");

	printf("Couleurs : { ROUGE, VERT, NOIR, BLANC }\n");
	printf("Connectivité : { 4G, 5G }\n");
	printf("Memoire : { 128GO, 256GO, 512GO }\n");
	printf("Mode de paiement : { ACHAT, LOCATION }\n");


	printf("=========================================\n");	

	set_location_modele_params_1_arg.id_location = 0;
	set_location_modele_params_1_arg.params_modele.id_modele = 1;
	set_location_modele_params_1_arg.params_modele.couleur = ROUGE;
	set_location_modele_params_1_arg.params_modele.connectivite = G4;
	set_location_modele_params_1_arg.params_modele.memoire = GO256;
	set_location_modele_params_1_arg.params_modele.mode_achat = location;

	printf("Enregistrement des parametres du modele\n");

	result_9 = set_location_modele_params_1(&set_location_modele_params_1_arg, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Enregistrement des parametres effectué\n");

	printf("=========================================\n");	

	printf("Recuperation des assurances\n");	

	result_10 = get_assurances_1((void*)&get_assurances_1_arg, clnt);
	if (result_10 == (listeAssurances *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Affichage des assurances\n");

		for (int i = 0; i < result_10->nb_assurances; i++)
		{
			printf("\nAssurance n°%d\n", i);
			afficherAssurances(result_10->assurances[i]);
		}
	}

	printf("=========================================\n");

	set_location_assurance_1_arg.id_location = 0;
	set_location_assurance_1_arg.id_assurance = 1;

	printf("Enregistrement de l'assurance pour la location\n");	

	result_11 = set_location_assurance_1(&set_location_assurance_1_arg, clnt);
	if (result_11 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Enregistrement de l'assurance effectué\n");	


	printf("=========================================\n");

	set_location_date_1_arg.id_location = 0;
	set_location_date_1_arg.date_livraison.jour = 14;
	set_location_date_1_arg.date_livraison.mois = 10;
	set_location_date_1_arg.date_livraison.annee = 2021;

	printf("Enregistrement de la date de livraison\n");	

	result_12 = set_location_date_1(&set_location_date_1_arg, clnt);
	if (result_12 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
		
	printf("Enregistrement de la date de livraison effectué\n");	

	printf("=========================================\n");

	confirmer_location_1_arg = 0;

	printf("Confirmation de la location\n");	

	result_13 = confirmer_location_1(&confirmer_location_1_arg, clnt);
	if (result_13 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Location de la livraison\n");

	printf("=========================================\n");
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	up2uservice_1 (host);
exit (0);
}
