/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "up2UService.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
init_1(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, INIT,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

s_client *
create_client_1(p_create_client *argp, CLIENT *clnt)
{
	static s_client clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CREATE_CLIENT,
		(xdrproc_t) xdr_p_create_client, (caddr_t) argp,
		(xdrproc_t) xdr_s_client, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

s_client *
set_client_1(p_set_client *argp, CLIENT *clnt)
{
	static s_client clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SET_CLIENT,
		(xdrproc_t) xdr_p_set_client, (caddr_t) argp,
		(xdrproc_t) xdr_s_client, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
init_location_1(void *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, INIT_LOCATION,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

listeClients *
get_clients_1(void *argp, CLIENT *clnt)
{
	static listeClients clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_CLIENTS,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_listeClients, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

s_client *
get_client_1(int *argp, CLIENT *clnt)
{
	static s_client clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_CLIENT,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_s_client, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

s_location *
set_location_client_1(s_client *argp, CLIENT *clnt)
{
	static s_location clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SET_LOCATION_CLIENT,
		(xdrproc_t) xdr_s_client, (caddr_t) argp,
		(xdrproc_t) xdr_s_location, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

listeModeles *
get_mobiles_1(void *argp, CLIENT *clnt)
{
	static listeModeles clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_MOBILES,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_listeModeles, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

p_params_mobile *
get_mobile_params_1(void *argp, CLIENT *clnt)
{
	static p_params_mobile clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_MOBILE_PARAMS,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_p_params_mobile, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

p_params_mobile *
set_params_mobile_1(p_params_mobile *argp, CLIENT *clnt)
{
	static p_params_mobile clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SET_PARAMS_MOBILE,
		(xdrproc_t) xdr_p_params_mobile, (caddr_t) argp,
		(xdrproc_t) xdr_p_params_mobile, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

s_location *
set_location_mobile_1(p_location_mobile *argp, CLIENT *clnt)
{
	static s_location clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SET_LOCATION_MOBILE,
		(xdrproc_t) xdr_p_location_mobile, (caddr_t) argp,
		(xdrproc_t) xdr_s_location, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

listeAssurances *
get_assurances_1(void *argp, CLIENT *clnt)
{
	static listeAssurances clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_ASSURANCES,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_listeAssurances, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

s_location *
set_location_assurances_1(p_location_assurance *argp, CLIENT *clnt)
{
	static s_location clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SET_LOCATION_ASSURANCES,
		(xdrproc_t) xdr_p_location_assurance, (caddr_t) argp,
		(xdrproc_t) xdr_s_location, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

p_create_livraison *
create_livraison_1(p_create_livraison *argp, CLIENT *clnt)
{
	static p_create_livraison clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CREATE_LIVRAISON,
		(xdrproc_t) xdr_p_create_livraison, (caddr_t) argp,
		(xdrproc_t) xdr_p_create_livraison, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
