/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "up2UService.h"


void
up2uservice_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *init_1_arg;
	s_client  *result_2;
	p_create_client  create_client_1_arg;
	s_client  *result_3;
	p_set_client  set_client_1_arg;
	int  *result_4;
	char *init_location_1_arg;
	listeClients  *result_5;
	char *get_clients_1_arg;
	s_client  *result_6;
	int  get_client_1_arg;
	s_location  *result_7;
	s_client  set_location_client_1_arg;
	listeModeles  *result_8;
	char *get_mobiles_1_arg;
	p_params_mobile  *result_9;
	char *get_mobile_params_1_arg;
	p_params_mobile  *result_10;
	p_params_mobile  set_params_mobile_1_arg;
	s_location  *result_11;
	p_location_mobile  set_location_mobile_1_arg;
	listeAssurances  *result_12;
	char *get_assurances_1_arg;
	s_location  *result_13;
	p_location_assurance  set_location_assurances_1_arg;
	p_create_livraison  *result_14;
	p_create_livraison  create_livraison_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, UP2USERVICE, UP2USERVICE_V_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = init_1((void*)&init_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = create_client_1(&create_client_1_arg, clnt);
	if (result_2 == (s_client *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = set_client_1(&set_client_1_arg, clnt);
	if (result_3 == (s_client *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = init_location_1((void*)&init_location_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = get_clients_1((void*)&get_clients_1_arg, clnt);
	if (result_5 == (listeClients *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = get_client_1(&get_client_1_arg, clnt);
	if (result_6 == (s_client *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = set_location_client_1(&set_location_client_1_arg, clnt);
	if (result_7 == (s_location *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = get_mobiles_1((void*)&get_mobiles_1_arg, clnt);
	if (result_8 == (listeModeles *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = get_mobile_params_1((void*)&get_mobile_params_1_arg, clnt);
	if (result_9 == (p_params_mobile *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = set_params_mobile_1(&set_params_mobile_1_arg, clnt);
	if (result_10 == (p_params_mobile *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = set_location_mobile_1(&set_location_mobile_1_arg, clnt);
	if (result_11 == (s_location *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = get_assurances_1((void*)&get_assurances_1_arg, clnt);
	if (result_12 == (listeAssurances *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = set_location_assurances_1(&set_location_assurances_1_arg, clnt);
	if (result_13 == (s_location *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_14 = create_livraison_1(&create_livraison_1_arg, clnt);
	if (result_14 == (p_create_livraison *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	up2uservice_1 (host);
exit (0);
}
