/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "up2UService.h"

void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

s_client *
create_client_1_svc(p_create_client *argp, struct svc_req *rqstp)
{
	static s_client  result;

	/*
	 * insert server code here
	 */

	return &result;
}

s_client *
set_client_1_svc(p_set_client *argp, struct svc_req *rqstp)
{
	static s_client  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
init_location_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

listeClients *
get_clients_1_svc(void *argp, struct svc_req *rqstp)
{
	static listeClients  result;

	/*
	 * insert server code here
	 */

	return &result;
}

s_client *
get_client_1_svc(int *argp, struct svc_req *rqstp)
{
	static s_client  result;

	/*
	 * insert server code here
	 */

	return &result;
}

s_location *
set_location_client_1_svc(s_client *argp, struct svc_req *rqstp)
{
	static s_location  result;

	/*
	 * insert server code here
	 */

	return &result;
}

listeModeles *
get_mobiles_1_svc(void *argp, struct svc_req *rqstp)
{
	static listeModeles  result;

	/*
	 * insert server code here
	 */

	return &result;
}

p_params_mobile *
get_mobile_params_1_svc(void *argp, struct svc_req *rqstp)
{
	static p_params_mobile  result;

	/*
	 * insert server code here
	 */

	return &result;
}

p_params_mobile *
set_params_mobile_1_svc(p_params_mobile *argp, struct svc_req *rqstp)
{
	static p_params_mobile  result;

	/*
	 * insert server code here
	 */

	return &result;
}

s_location *
set_location_mobile_1_svc(p_location_mobile *argp, struct svc_req *rqstp)
{
	static s_location  result;

	/*
	 * insert server code here
	 */

	return &result;
}

listeAssurances *
get_assurances_1_svc(void *argp, struct svc_req *rqstp)
{
	static listeAssurances  result;

	/*
	 * insert server code here
	 */

	return &result;
}

s_location *
set_location_assurances_1_svc(p_location_assurance *argp, struct svc_req *rqstp)
{
	static s_location  result;

	/*
	 * insert server code here
	 */

	return &result;
}

p_create_livraison *
create_livraison_1_svc(p_create_livraison *argp, struct svc_req *rqstp)
{
	static p_create_livraison  result;

	/*
	 * insert server code here
	 */

	return &result;
}
