/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "up2UService.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
up2uservice_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		p_create_client create_client_1_arg;
		p_set_client set_client_1_arg;
		p_location_client set_location_client_1_arg;
		int set_location_modele_1_arg;
		int get_modele_params_1_arg;
		p_location_params_modele set_location_modele_params_1_arg;
		p_location_assurance set_location_assurance_1_arg;
		p_location_date set_location_date_1_arg;
		int confirmer_location_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INIT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) init_1_svc;
		break;

	case CREATE_CLIENT:
		_xdr_argument = (xdrproc_t) xdr_p_create_client;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) create_client_1_svc;
		break;

	case SET_CLIENT:
		_xdr_argument = (xdrproc_t) xdr_p_set_client;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) set_client_1_svc;
		break;

	case GET_CLIENTS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_listeClients;
		local = (char *(*)(char *, struct svc_req *)) get_clients_1_svc;
		break;

	case SET_LOCATION_CLIENT:
		_xdr_argument = (xdrproc_t) xdr_p_location_client;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) set_location_client_1_svc;
		break;

	case GET_MODELES:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_listeModeles;
		local = (char *(*)(char *, struct svc_req *)) get_modeles_1_svc;
		break;

	case SET_LOCATION_MODELE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) set_location_modele_1_svc;
		break;

	case GET_MODELE_PARAMS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_listeModelesParams;
		local = (char *(*)(char *, struct svc_req *)) get_modele_params_1_svc;
		break;

	case SET_LOCATION_MODELE_PARAMS:
		_xdr_argument = (xdrproc_t) xdr_p_location_params_modele;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) set_location_modele_params_1_svc;
		break;

	case GET_ASSURANCES:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_listeAssurances;
		local = (char *(*)(char *, struct svc_req *)) get_assurances_1_svc;
		break;

	case SET_LOCATION_ASSURANCE:
		_xdr_argument = (xdrproc_t) xdr_p_location_assurance;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) set_location_assurance_1_svc;
		break;

	case SET_LOCATION_DATE:
		_xdr_argument = (xdrproc_t) xdr_p_location_date;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) set_location_date_1_svc;
		break;

	case CONFIRMER_LOCATION:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) confirmer_location_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (UP2USERVICE, UP2USERVICE_V_1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, UP2USERVICE, UP2USERVICE_V_1, up2uservice_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (UP2USERVICE, UP2USERVICE_V_1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, UP2USERVICE, UP2USERVICE_V_1, up2uservice_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (UP2USERVICE, UP2USERVICE_V_1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
