/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "up2UService.h"

void afficherClient(s_client client)
{
	printf("%s\n", client.nom);
	printf("%s\n", client.prenom);
	printf("%d %s %d\n", client.adresse.numeroRue, client.adresse.rue, client.adresse.codePostal);
	printf("%ld %d %d/%d\n", client.coord_bc.numero, client.coord_bc.crypto, client.coord_bc.mois, client.coord_bc.annee);
}

void afficherModele(s_modele modele)
{
	printf("%s\n", modele.nom);
	printf("Prix d'achat : %d\n", modele.prix_achat);
	printf("Prix de location : %d\n", modele.prix_location);
	printf("%s\n", modele.description);
}

void
up2uservice_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *init_1_arg;
	int  *result_2;
	p_create_client  create_client_1_arg;
	int  *result_3;
	p_set_client  set_client_1_arg;
	listeClients  *result_4;
	char *get_clients_1_arg;
	int  *result_5;
	p_location_client  set_location_client_1_arg;
	listeModeles  *result_6;
	char *get_modeles_1_arg;
	int  *result_7;
	p_location_modele  set_location_modele_1_arg;
	listeModelesParams  *result_8;
	int  get_modele_params_1_arg;
	int  *result_9;
	p_location_params_modele  set_location_modele_params_1_arg;
	listeAssurances  *result_10;
	char *get_assurances_1_arg;
	int  *result_11;
	p_location_assurance  set_location_assurance_1_arg;
	int  *result_12;
	p_location_date  set_location_date_1_arg;
	int  *result_13;
	int  confirmer_location_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, UP2USERVICE, UP2USERVICE_V_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = init_1((void*)&init_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Serveur initialisé !\n");

	printf("=========================================\n");

	strcpy(create_client_1_arg.nom, "DUPONT");
	strcpy(create_client_1_arg.prenom, "Jean");
	create_client_1_arg.adresse.codePostal = 36450;
	create_client_1_arg.adresse.numeroRue = 12;
	strcpy(create_client_1_arg.adresse.rue, "Chemin del papa");
	create_client_1_arg.coord_bc.numero = 6412333356766934;
	create_client_1_arg.coord_bc.crypto = 373;
	create_client_1_arg.coord_bc.mois = 12;
	create_client_1_arg.coord_bc.annee = 2025;

	printf("Ajout du client\n");

	result_2 = create_client_1(&create_client_1_arg, clnt);
	if (result_2 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	printf("Client ajouté\n");

	printf("=========================================\n");

	set_client_1_arg.id = 2;
	strcpy(set_client_1_arg.nom, "CASTEX");
	strcpy(set_client_1_arg.prenom, "Janot");
	set_client_1_arg.coord_bc.numero = 6412374856766934;
	set_client_1_arg.coord_bc.crypto = 694;
	set_client_1_arg.coord_bc.mois = 01;
	set_client_1_arg.coord_bc.annee = 2024;
	set_client_1_arg.adresse.codePostal = 22600;
	set_client_1_arg.adresse.numeroRue = 45;
	strcpy(set_client_1_arg.adresse.rue, "Chemin du paradis");

	printf("Modification du client\n");

	result_3 = set_client_1(&set_client_1_arg, clnt);
	if (result_3 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	printf("Modification du client effectué\n");

	printf("=========================================\n");

	printf("Affichage des clients\n");
	result_4 = get_clients_1((void *)&get_clients_1_arg, clnt);
	if (result_4 == (listeClients *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	for (int i = 0; i < result_4->nb_clients; i++)
	{
		printf("\nClient n°%d\n", i);
		afficherClient(result_4->client[i]);
	}

	printf("=========================================\n");

	set_location_client_1_arg.id_location = 0;
	set_location_client_1_arg.id_client = 2;

	printf("Enregistrement du client pour la location\n");

	result_5 = set_location_client_1(&set_location_client_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Enregistrement du client effectué\n");

	printf("=========================================\n");
	
	printf("Affichage des modeles\n");
	
	result_6 = get_modeles_1((void*)&get_modeles_1_arg, clnt);
	if (result_6 == (listeModeles *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	//printf("%s\n",result_6->modeles[0].id);

	// for (int i = 0; i < result_6->nb_modeles; i++)
	// {
	// 	printf("\nModele n°%d\n", i);
	// 	afficherModele(result_6->modeles[i]);
	// }

	printf("=========================================\n");

	set_location_modele_1_arg.id_location = 0;
	set_location_modele_1_arg.id_modele = 1;

	printf("Enregistrement du modele pour la location\n");

	result_7 = set_location_modele_1(&set_location_modele_1_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Enregistrement du modele effectué\n");

	printf("=========================================\n");

	result_8 = get_modele_params_1(&get_modele_params_1_arg, clnt);
	if (result_8 == (listeModelesParams *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = set_location_modele_params_1(&set_location_modele_params_1_arg, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = get_assurances_1((void*)&get_assurances_1_arg, clnt);
	if (result_10 == (listeAssurances *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = set_location_assurance_1(&set_location_assurance_1_arg, clnt);
	if (result_11 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = set_location_date_1(&set_location_date_1_arg, clnt);
	if (result_12 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = confirmer_location_1(&confirmer_location_1_arg, clnt);
	if (result_13 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	up2uservice_1 (host);
exit (0);
}
